export const SEARCH_FOCUS = 'header/search_focus'
export const SEARCH_NOT_FOCUS = 'header/search_not_focus'
export const CHANGE_LIST = 'header/change_list'
export const MOUSE_ENTER = 'header/mouse_enter'
export const MOUSE_LEAVE = 'header/mouse_leave'
export const CHANGE_PAGE = 'header/change_page'